// FORMS-F4 — `kind = 'FORM'` on the write policies, probed as a 2×2.
//
// ─────────────────────────────────────────────────────────────────────────────
// F-04 IN ONE LINE
//
// `form_templates` is one physical table holding two different objects: FORMs
// (standalone templates that own records, a numbering counter and, since
// 2026-09-01, possibly a public link) and BLOCKs (reusable fragments embedded
// into CAPA, Change Request and QC checklist steps). The product presents them
// as two modules — `forms_templates` and `form_blocks` — and grants them
// independently in Role & Permission Management.
//
// The write policies did not know that. `form_templates_{ins,upd,del}` carried
// a tenant predicate and a `forms_templates` permission check and NO `kind`
// clause, so anyone holding `forms_templates:update` could rewrite the seeded
// `TASK` and `IMPACT-CHK` blocks — the fragments every CAPA and Change Request
// child step is built from — while holding no `form_blocks` grant at all.
//
// `AND kind = 'FORM'` closed it. One conjunct is exactly the size of edit a
// regression undoes silently, and the eight policies governing this table
// previously existed in NO SOURCE FILE — four generated by
// `authz.apply_module_rls`, four hand-written in a 2026-07 migration — so
// there was not even a file to review the change in. There is now (`rls.sql`),
// and this is the test.
//
// ─────────────────────────────────────────────────────────────────────────────
// WHY A 2×2 AND NOT A DENIAL
//
// An RLS refusal on an UPDATE is a ZERO-ROW SUCCESS. Nothing throws, nothing
// 403s; the statement simply matches no rows and psql prints `UPDATE 0`. So
// `expect().rejects` would be the wrong assertion, and a one-sided "the forms
// designer cannot touch the block" is worth nothing — it passes identically
// when the persona has no grants, when the fixture row is missing, when the
// policy was dropped outright, and when `app_user` lost its table GRANT.
//
// The 2×2 removes every one of those readings, because each cell's denial has
// an admission next to it in BOTH directions:
//
//                        UPDATE a FORM row     UPDATE a BLOCK row
//   formsDesigner              1                      0     ← F-04, closed
//   blockDesigner              0                      1     ← the mirror
//
// Read across a row: the persona's grant works, so the persona is real and the
// policy is live. Read down a column: the row is reachable, so the row is real
// and `app_user` holds the privilege. The ONLY difference between the two
// columns is `kind`. Nothing else in this table can explain the diagonal.
//
// ─────────────────────────────────────────────────────────────────────────────
// MEASURED (app-db, 2026-09-01, `SET ROLE app_user` + the real request path's GUCs)
//
//   formsDesigner  has_permission('forms_templates','update') = true
//                  has_permission('form_blocks','update')     = false
//   blockDesigner  the exact mirror
//   the four UPDATEs: 1 / 0 / 0 / 1, as tabulated above.
//
// `authz.module_actions` for both modules is {create, update, delete} — neither
// declares `read`, which is why the SELECT side below reads the way it does.
import { test, expect } from '@playwright/test'
import { COMPANY_ID } from '../fixtures/cast.js'
import { sqlAsAppUser, sqlValue } from '../fixtures/db.js'
import { FORMS, FORMS_PERSONAS, affectedRows, ensureFormsFixtures } from '../fixtures/forms.js'

const FORM_ROW = FORMS.rlsForm
const BLOCK_ROW = FORMS.block

/** `authz.has_permission`, evaluated exactly as the policy evaluates it. */
function hasPermission(userId, moduleId, action) {
  const res = sqlAsAppUser(
    `SELECT 'RESULT=' || authz.has_permission('${moduleId}', '${action}')::text;`,
    { userId, companyId: COMPANY_ID },
  )
  expect(res.ok, `permission probe ran (stderr: ${res.error})`).toBeTruthy()
  const m = /RESULT=(true|false)/.exec(res.output)
  expect(m, `permission probe returned a boolean (output: ${res.output})`).not.toBeNull()
  return m[1] === 'true'
}

/**
 * Attempt a harmless UPDATE and report how many rows it touched.
 *
 * `title = title` is a genuine UPDATE as far as the policy is concerned — the
 * row is located, the USING clause is evaluated, and the WITH CHECK clause is
 * evaluated against the new tuple — while leaving the fixture byte-identical, so
 * the probe can run as often as it likes and in any order.
 */
function tryUpdate(userId, templateId) {
  const res = sqlAsAppUser(
    `UPDATE form_templates SET title = title WHERE id = '${templateId}';`,
    { userId, companyId: COMPANY_ID },
  )
  expect(
    res.ok,
    `the statement must SUCCEED (against 0 or 1 rows); it raised instead: ${res.error}`,
  ).toBeTruthy()
  const n = affectedRows(res)
  expect(n, `a row count was readable off the command tag (output: ${res.output})`).not.toBeNull()
  return n
}

test.beforeAll(() => {
  ensureFormsFixtures()

  // The premise, taken with RLS bypassed. Without this the whole 2×2 is
  // consistent with "there is no BLOCK row in this tenant".
  expect(
    sqlValue(`SELECT kind FROM form_templates WHERE id = '${FORM_ROW.id}'`),
    'the FORM column of the matrix has a FORM in it',
  ).toBe('FORM')
  expect(
    sqlValue(`SELECT kind FROM form_templates WHERE id = '${BLOCK_ROW.id}'`),
    'and the BLOCK column has a BLOCK',
  ).toBe('BLOCK')
  expect(
    sqlValue(
      `SELECT count(*) FROM form_templates WHERE id IN ('${FORM_ROW.id}','${BLOCK_ROW.id}') AND company_id = '${COMPANY_ID}' AND deleted_at IS NULL`,
    ),
    'both rows are live in the tenant both personas belong to',
  ).toBe('2')
})

test.describe('FORMS-F4 — a forms grant does not govern form blocks', () => {
  test('the two personas hold exactly one module each, and nothing of the other', () => {
    // The grants first, because every cell of the matrix is a claim about them.
    // If a future seed edit widened either role, the matrix would still be
    // internally consistent and would have stopped testing F-04 — this is the
    // assertion that notices.
    for (const action of ['create', 'update', 'delete']) {
      expect(
        hasPermission(FORMS_PERSONAS.formsDesigner.id, 'forms_templates', action),
        `the forms designer holds forms_templates:${action}`,
      ).toBe(true)
      expect(
        hasPermission(FORMS_PERSONAS.formsDesigner.id, 'form_blocks', action),
        `…and no form_blocks:${action}`,
      ).toBe(false)

      expect(
        hasPermission(FORMS_PERSONAS.blockDesigner.id, 'form_blocks', action),
        `the block designer holds form_blocks:${action}`,
      ).toBe(true)
      expect(
        hasPermission(FORMS_PERSONAS.blockDesigner.id, 'forms_templates', action),
        `…and no forms_templates:${action}`,
      ).toBe(false)
    }
  })

  test('the write matrix is diagonal — and `kind` is the only thing on the diagonal', () => {
    const forms = FORMS_PERSONAS.formsDesigner.id
    const blocks = FORMS_PERSONAS.blockDesigner.id

    // ── Row 1: the finding. ─────────────────────────────────────────────────
    expect(
      tryUpdate(forms, FORM_ROW.id),
      'the forms designer edits a FORM — so the persona, the grant and the policy all work',
    ).toBe(1)
    expect(
      tryUpdate(forms, BLOCK_ROW.id),
      'F-04: the same grant, the same table, the same tenant — and a BLOCK is out of reach. ' +
        'Before `AND kind = \'FORM\'` this returned 1, and every CAPA/CR child step was rewritable ' +
        'by anyone holding forms_templates:update.',
    ).toBe(0)

    // ── Row 2: the mirror, which is what makes row 1 evidence. ──────────────
    expect(
      tryUpdate(blocks, BLOCK_ROW.id),
      'the block designer edits a BLOCK — so the BLOCK row is reachable and app_user holds UPDATE on the table',
    ).toBe(1)
    expect(
      tryUpdate(blocks, FORM_ROW.id),
      'and a form_blocks grant does not reach a FORM either — the partition cuts both ways',
    ).toBe(0)

    // The policy text, so a revert fails here by name rather than as an
    // arithmetic surprise three assertions up.
    for (const policy of ['form_templates_upd', 'form_templates_ins', 'form_templates_del']) {
      const expr = sqlValue(
        `SELECT coalesce(pg_get_expr(polqual, polrelid), pg_get_expr(polwithcheck, polrelid))
           FROM pg_policy WHERE polname = '${policy}'`,
      )
      expect(expr, `${policy} exists`).not.toBeNull()
      // `pg_get_expr` re-renders the varchar comparison with its casts —
      // `((kind)::text = 'FORM'::text)`, not the `kind = 'FORM'` that rls.sql
      // spells. Matching either form, so this assertion tracks the SEMANTICS and
      // does not fail the day somebody adds a cast or drops one.
      expect(expr, `${policy} carries the kind predicate`).toMatch(
        /\(?kind\)?(::text)? = 'FORM'/,
      )
      expect(expr, `${policy} still names its own module`).toContain("'forms_templates'")
    }
  })

  test('INSERT is partitioned the same way', () => {
    // The UPDATE policy is where the finding was demonstrated, but `_ins`
    // carries the same conjunct and would be the natural way to get a BLOCK into
    // the table without a form_blocks grant. INSERT has no silent-zero-row
    // failure mode: a WITH CHECK violation RAISES 42501, so this half is probed
    // with `ok`, not with a row count.
    const forms = FORMS_PERSONAS.formsDesigner.id
    // `created_at`, `updated_at` and `config` are NOT NULL with no default —
    // Sequelize supplies them, raw SQL has to. Supplied so a failure here can
    // only be the policy.
    const mk = (kind, code) =>
      `INSERT INTO form_templates (company_id, title, code, kind, status_id, version, schema, config, created_at, updated_at)
         VALUES ('${COMPANY_ID}', 'F4 probe ${code}', '${code}', '${kind}', 'DRAFT', 1, '[]'::jsonb, '{}'::jsonb, NOW(), NOW());`

    const asBlock = sqlAsAppUser(mk('BLOCK', `F4B${Date.now() % 100000}`), {
      userId: forms,
      companyId: COMPANY_ID,
    })
    expect(
      asBlock.ok,
      'a forms_templates:create grant cannot mint a BLOCK — the row-security policy refuses it',
    ).toBe(false)
    expect(asBlock.error, 'and it is refused as a privilege error, not swallowed').toMatch(
      /row-level security|42501/i,
    )

    // Paired: the same persona, the same statement, kind = 'FORM' — accepted.
    // Rolled back immediately; the point is the acceptance, not the row.
    const code = `F4F${Date.now() % 100000}`
    const asForm = sqlAsAppUser(`BEGIN; ${mk('FORM', code)} ROLLBACK;`, {
      userId: forms,
      companyId: COMPANY_ID,
    })
    expect(
      asForm.ok,
      `the same grant DOES mint a FORM, so the refusal above is about kind (stderr: ${asForm.error})`,
    ).toBe(true)
    expect(
      sqlValue(`SELECT count(*) FROM form_templates WHERE code = '${code}'`),
      'and the probe left nothing behind',
    ).toBe('0')
  })

  test('⚠ READS are NOT partitioned — a documented open item, asserted as it stands', () => {
    // THIS TEST ASSERTS CURRENT REAL BEHAVIOUR THAT IS NOT THE DESIRED END STATE.
    //
    // `form_templates_sel` is tenancy-only, with no permission predicate at all,
    // and `rls.sql` says so in a comment beside it: `forms_templates` has NO
    // `read` action in the catalog (measured — only create/update/delete rows
    // exist), so `has_permission('forms_templates','read')` would hit the
    // accessor's read-fallback (`OR p_action = 'read'`) and match ANY grant on
    // the module — a gate that reads as one and is not. Meanwhile DynamicForm
    // has 35 consumers that all resolve a template to render. Narrowing the read
    // is real work with a real blast radius and was recorded as open rather than
    // half-done.
    //
    // The consequence, measured: BOTH personas read BOTH kinds. A form designer
    // sees the seeded blocks; a block designer sees every form in the tenant.
    // `form_templates_blk_sel` is consequently redundant — the tenancy policy
    // already admits every row it admits — and is kept only so the block family
    // stays symmetric and survives a future read change.
    //
    // When that read change lands, this test SHOULD fail. The failure is the
    // signal to rewrite it, not a regression.
    const seen = (userId) => {
      const res = sqlAsAppUser(
        `SELECT 'RESULT=' || count(*) FILTER (WHERE kind = 'FORM')::text || ':' ||
                              count(*) FILTER (WHERE kind = 'BLOCK')::text
           FROM form_templates WHERE company_id = '${COMPANY_ID}';`,
        { userId, companyId: COMPANY_ID },
      )
      expect(res.ok, `read probe ran (stderr: ${res.error})`).toBeTruthy()
      const m = /RESULT=(\d+):(\d+)/.exec(res.output)
      expect(m, `read probe returned two counts (output: ${res.output})`).not.toBeNull()
      return { forms: Number(m[1]), blocks: Number(m[2]) }
    }

    const byForms = seen(FORMS_PERSONAS.formsDesigner.id)
    const byBlocks = seen(FORMS_PERSONAS.blockDesigner.id)

    expect(byForms.blocks, 'the forms designer reads BLOCKs — they just cannot write them').toBeGreaterThan(0)
    expect(byBlocks.forms, 'and the block designer reads FORMs').toBeGreaterThan(0)
    expect(byForms, 'in fact the two see exactly the same table — reads are tenancy-only').toEqual(
      byBlocks,
    )

    // The tenant boundary, which the read policy DOES enforce, is the half that
    // must never regress while the permission half stays open.
    for (const persona of Object.values(FORMS_PERSONAS)) {
      const res = sqlAsAppUser(
        `SELECT 'RESULT=' || count(*)::text FROM form_templates WHERE company_id <> '${COMPANY_ID}';`,
        { userId: persona.id, companyId: COMPANY_ID },
      )
      expect(res.ok, `cross-tenant read probe ran (stderr: ${res.error})`).toBeTruthy()
      expect(
        Number(/RESULT=(\d+)/.exec(res.output)?.[1]),
        `${persona.name} reads no other tenant’s templates`,
      ).toBe(0)
    }
    // …paired, so "zero rows" is not simply what this query always returns.
    expect(
      Number(sqlValue(`SELECT count(*) FROM form_templates WHERE company_id <> '${COMPANY_ID}'`)),
      'there are other tenants’ templates to leak',
    ).toBeGreaterThan(0)
  })
})
