/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/accept-invitation': RouteRecordInfo<
      '/accept-invitation',
      '/accept-invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/impersonate/[[companyId]]': RouteRecordInfo<
      '/admin/impersonate/[[companyId]]',
      '/admin/impersonate/:companyId?',
      { companyId?: ParamValueZeroOrOne<true> },
      { companyId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/admin-security': RouteRecordInfo<
      '/admin-security',
      '/admin-security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai-usage': RouteRecordInfo<
      '/ai-usage',
      '/ai-usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-keys': RouteRecordInfo<
      '/api-keys',
      '/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-tokens': RouteRecordInfo<
      '/api-tokens',
      '/api-tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/asset-request/[token]': RouteRecordInfo<
      '/asset-request/[token]',
      '/asset-request/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/audit-logs': RouteRecordInfo<
      '/audit-logs',
      '/audit-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audits/': RouteRecordInfo<
      '/audits/',
      '/audits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audits/instances/[id]': RouteRecordInfo<
      '/audits/instances/[id]',
      '/audits/instances/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/audits/programs/[id]': RouteRecordInfo<
      '/audits/programs/[id]',
      '/audits/programs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/audits/standards/[id]': RouteRecordInfo<
      '/audits/standards/[id]',
      '/audits/standards/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/automation-rules': RouteRecordInfo<
      '/automation-rules',
      '/automation-rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/capas/[[id]]': RouteRecordInfo<
      '/capas/[[id]]',
      '/capas/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/change-requests/[[id]]': RouteRecordInfo<
      '/change-requests/[[id]]',
      '/change-requests/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/complaint-settings': RouteRecordInfo<
      '/complaint-settings',
      '/complaint-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/custom-fields': RouteRecordInfo<
      '/custom-fields',
      '/custom-fields',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/customer-complaints/[[id]]': RouteRecordInfo<
      '/customer-complaints/[[id]]',
      '/customer-complaints/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/customer-complaints/reports': RouteRecordInfo<
      '/customer-complaints/reports',
      '/customer-complaints/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/departments': RouteRecordInfo<
      '/departments',
      '/departments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/document-templates/[[id]]': RouteRecordInfo<
      '/document-templates/[[id]]',
      '/document-templates/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/documents/[[id]]': RouteRecordInfo<
      '/documents/[[id]]',
      '/documents/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/documents/print': RouteRecordInfo<
      '/documents/print',
      '/documents/print',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/equipment/': RouteRecordInfo<
      '/equipment/',
      '/equipment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password': RouteRecordInfo<
      '/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/form/[templateId]': RouteRecordInfo<
      '/form/[templateId]',
      '/form/:templateId',
      { templateId: ParamValue<true> },
      { templateId: ParamValue<false> },
      | never
    >,
    '/form-templates': RouteRecordInfo<
      '/form-templates',
      '/form-templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/groups/[[id]]': RouteRecordInfo<
      '/groups/[[id]]',
      '/groups/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/help/': RouteRecordInfo<
      '/help/',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help/[...slug]': RouteRecordInfo<
      '/help/[...slug]',
      '/help/:slug(.*)',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/inspections-logs/': RouteRecordInfo<
      '/inspections-logs/',
      '/inspections-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspections-logs/fill': RouteRecordInfo<
      '/inspections-logs/fill',
      '/inspections-logs/fill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspections-logs/form-assignments/': RouteRecordInfo<
      '/inspections-logs/form-assignments/',
      '/inspections-logs/form-assignments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspections-logs/form-assignments/[id]': RouteRecordInfo<
      '/inspections-logs/form-assignments/[id]',
      '/inspections-logs/form-assignments/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/inspections-logs/form-assignments/create': RouteRecordInfo<
      '/inspections-logs/form-assignments/create',
      '/inspections-logs/form-assignments/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspections-logs/log-books/[id]': RouteRecordInfo<
      '/inspections-logs/log-books/[id]',
      '/inspections-logs/log-books/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/inspections-logs/queue': RouteRecordInfo<
      '/inspections-logs/queue',
      '/inspections-logs/queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspections-logs/records': RouteRecordInfo<
      '/inspections-logs/records',
      '/inspections-logs/records',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inspections-logs/templates': RouteRecordInfo<
      '/inspections-logs/templates',
      '/inspections-logs/templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logging': RouteRecordInfo<
      '/logging',
      '/logging',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/lookups': RouteRecordInfo<
      '/lookups',
      '/lookups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/m/[moduleKey]/[[id]]': RouteRecordInfo<
      '/m/[moduleKey]/[[id]]',
      '/m/:moduleKey/:id?',
      { moduleKey: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { moduleKey: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/my-training/[id]': RouteRecordInfo<
      '/my-training/[id]',
      '/my-training/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/no-access': RouteRecordInfo<
      '/no-access',
      '/no-access',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nonconformances/[[id]]': RouteRecordInfo<
      '/nonconformances/[[id]]',
      '/nonconformances/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/notification-rules': RouteRecordInfo<
      '/notification-rules',
      '/notification-rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notifications': RouteRecordInfo<
      '/notifications',
      '/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/option-sets/[[id]]': RouteRecordInfo<
      '/option-sets/[[id]]',
      '/option-sets/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/organization-security': RouteRecordInfo<
      '/organization-security',
      '/organization-security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/': RouteRecordInfo<
      '/platform/',
      '/platform',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/admins': RouteRecordInfo<
      '/platform/admins',
      '/platform/admins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/audit': RouteRecordInfo<
      '/platform/audit',
      '/platform/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/companies/': RouteRecordInfo<
      '/platform/companies/',
      '/platform/companies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/companies/[id]': RouteRecordInfo<
      '/platform/companies/[id]',
      '/platform/companies/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/platform/plans': RouteRecordInfo<
      '/platform/plans',
      '/platform/plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/print': RouteRecordInfo<
      '/print',
      '/print',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products/[[id]]': RouteRecordInfo<
      '/products/[[id]]',
      '/products/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qc-inspection/': RouteRecordInfo<
      '/qc-inspection/',
      '/qc-inspection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qc-inspection/lots/[id]': RouteRecordInfo<
      '/qc-inspection/lots/[id]',
      '/qc-inspection/lots/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/qc-inspection/specifications/[id]': RouteRecordInfo<
      '/qc-inspection/specifications/[id]',
      '/qc-inspection/specifications/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/qualityEvents/[[id]]': RouteRecordInfo<
      '/qualityEvents/[[id]]',
      '/qualityEvents/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/qualityEvents/dashboard': RouteRecordInfo<
      '/qualityEvents/dashboard',
      '/qualityEvents/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rca-templates': RouteRecordInfo<
      '/rca-templates',
      '/rca-templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/records': RouteRecordInfo<
      '/records',
      '/records',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-esign-pin': RouteRecordInfo<
      '/reset-esign-pin',
      '/reset-esign-pin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/risk-assessment-templates': RouteRecordInfo<
      '/risk-assessment-templates',
      '/risk-assessment-templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roles/[[id]]': RouteRecordInfo<
      '/roles/[[id]]',
      '/roles/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/security': RouteRecordInfo<
      '/security',
      '/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signin': RouteRecordInfo<
      '/signin',
      '/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sites': RouteRecordInfo<
      '/sites',
      '/sites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/supplier/': RouteRecordInfo<
      '/supplier/',
      '/supplier',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/supplier/document-requests': RouteRecordInfo<
      '/supplier/document-requests',
      '/supplier/document-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/supplier-document/[token]': RouteRecordInfo<
      '/supplier-document/[token]',
      '/supplier-document/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/suppliers/[[id]]': RouteRecordInfo<
      '/suppliers/[[id]]',
      '/suppliers/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/support/[slug]': RouteRecordInfo<
      '/support/[slug]',
      '/support/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/support/ticket/[id]': RouteRecordInfo<
      '/support/ticket/[id]',
      '/support/ticket/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/task-instances': RouteRecordInfo<
      '/task-instances',
      '/task-instances',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/templates/[[id]]': RouteRecordInfo<
      '/templates/[[id]]',
      '/templates/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/training-instances/[[id]]': RouteRecordInfo<
      '/training-instances/[[id]]',
      '/training-instances/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/training-matrix': RouteRecordInfo<
      '/training-matrix',
      '/training-matrix',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/training-verifications/[[id]]': RouteRecordInfo<
      '/training-verifications/[[id]]',
      '/training-verifications/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/trainings/[[id]]': RouteRecordInfo<
      '/trainings/[[id]]',
      '/trainings/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/users/[[id]]': RouteRecordInfo<
      '/users/[[id]]',
      '/users/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/workflow-instances/[[id]]': RouteRecordInfo<
      '/workflow-instances/[[id]]',
      '/workflow-instances/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/workflow-templates/[[id]]': RouteRecordInfo<
      '/workflow-templates/[[id]]',
      '/workflow-templates/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/accept-invitation.vue': {
      routes:
        | '/accept-invitation'
      views:
        | never
    }
    'src/pages/admin/impersonate/[[companyId]].vue': {
      routes:
        | '/admin/impersonate/[[companyId]]'
      views:
        | never
    }
    'src/pages/admin-security.vue': {
      routes:
        | '/admin-security'
      views:
        | never
    }
    'src/pages/ai-usage.vue': {
      routes:
        | '/ai-usage'
      views:
        | never
    }
    'src/pages/api-keys.vue': {
      routes:
        | '/api-keys'
      views:
        | never
    }
    'src/pages/api-tokens.vue': {
      routes:
        | '/api-tokens'
      views:
        | never
    }
    'src/pages/asset-request/[token].vue': {
      routes:
        | '/asset-request/[token]'
      views:
        | never
    }
    'src/pages/audit-logs.vue': {
      routes:
        | '/audit-logs'
      views:
        | never
    }
    'src/pages/audits/index.vue': {
      routes:
        | '/audits/'
      views:
        | never
    }
    'src/pages/audits/instances/[id].vue': {
      routes:
        | '/audits/instances/[id]'
      views:
        | never
    }
    'src/pages/audits/programs/[id].vue': {
      routes:
        | '/audits/programs/[id]'
      views:
        | never
    }
    'src/pages/audits/standards/[id].vue': {
      routes:
        | '/audits/standards/[id]'
      views:
        | never
    }
    'src/pages/automation-rules.vue': {
      routes:
        | '/automation-rules'
      views:
        | never
    }
    'src/pages/capas/[[id]].vue': {
      routes:
        | '/capas/[[id]]'
      views:
        | never
    }
    'src/pages/change-requests/[[id]].vue': {
      routes:
        | '/change-requests/[[id]]'
      views:
        | never
    }
    'src/pages/complaint-settings.vue': {
      routes:
        | '/complaint-settings'
      views:
        | never
    }
    'src/pages/custom-fields.vue': {
      routes:
        | '/custom-fields'
      views:
        | never
    }
    'src/pages/customer-complaints/[[id]].vue': {
      routes:
        | '/customer-complaints/[[id]]'
      views:
        | never
    }
    'src/pages/customer-complaints/reports.vue': {
      routes:
        | '/customer-complaints/reports'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/departments.vue': {
      routes:
        | '/departments'
      views:
        | never
    }
    'src/pages/document-templates/[[id]].vue': {
      routes:
        | '/document-templates/[[id]]'
      views:
        | never
    }
    'src/pages/documents/[[id]].vue': {
      routes:
        | '/documents/[[id]]'
      views:
        | never
    }
    'src/pages/documents/print.vue': {
      routes:
        | '/documents/print'
      views:
        | never
    }
    'src/pages/equipment/index.vue': {
      routes:
        | '/equipment/'
      views:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | '/forgot-password'
      views:
        | never
    }
    'src/pages/form/[templateId].vue': {
      routes:
        | '/form/[templateId]'
      views:
        | never
    }
    'src/pages/form-templates.vue': {
      routes:
        | '/form-templates'
      views:
        | never
    }
    'src/pages/groups/[[id]].vue': {
      routes:
        | '/groups/[[id]]'
      views:
        | never
    }
    'src/pages/help/index.vue': {
      routes:
        | '/help/'
      views:
        | never
    }
    'src/pages/help/[...slug].vue': {
      routes:
        | '/help/[...slug]'
      views:
        | never
    }
    'src/pages/inspections-logs/index.vue': {
      routes:
        | '/inspections-logs/'
      views:
        | never
    }
    'src/pages/inspections-logs/fill.vue': {
      routes:
        | '/inspections-logs/fill'
      views:
        | never
    }
    'src/pages/inspections-logs/form-assignments/index.vue': {
      routes:
        | '/inspections-logs/form-assignments/'
      views:
        | never
    }
    'src/pages/inspections-logs/form-assignments/[id].vue': {
      routes:
        | '/inspections-logs/form-assignments/[id]'
      views:
        | never
    }
    'src/pages/inspections-logs/form-assignments/create.vue': {
      routes:
        | '/inspections-logs/form-assignments/create'
      views:
        | never
    }
    'src/pages/inspections-logs/log-books/[id].vue': {
      routes:
        | '/inspections-logs/log-books/[id]'
      views:
        | never
    }
    'src/pages/inspections-logs/queue.vue': {
      routes:
        | '/inspections-logs/queue'
      views:
        | never
    }
    'src/pages/inspections-logs/records.vue': {
      routes:
        | '/inspections-logs/records'
      views:
        | never
    }
    'src/pages/inspections-logs/templates.vue': {
      routes:
        | '/inspections-logs/templates'
      views:
        | never
    }
    'src/pages/logging.vue': {
      routes:
        | '/logging'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/lookups.vue': {
      routes:
        | '/lookups'
      views:
        | never
    }
    'src/pages/m/[moduleKey]/[[id]].vue': {
      routes:
        | '/m/[moduleKey]/[[id]]'
      views:
        | never
    }
    'src/pages/my-training/[id].vue': {
      routes:
        | '/my-training/[id]'
      views:
        | never
    }
    'src/pages/no-access.vue': {
      routes:
        | '/no-access'
      views:
        | never
    }
    'src/pages/nonconformances/[[id]].vue': {
      routes:
        | '/nonconformances/[[id]]'
      views:
        | never
    }
    'src/pages/notification-rules.vue': {
      routes:
        | '/notification-rules'
      views:
        | never
    }
    'src/pages/notifications.vue': {
      routes:
        | '/notifications'
      views:
        | never
    }
    'src/pages/option-sets/[[id]].vue': {
      routes:
        | '/option-sets/[[id]]'
      views:
        | never
    }
    'src/pages/organization-security.vue': {
      routes:
        | '/organization-security'
      views:
        | never
    }
    'src/pages/platform/index.vue': {
      routes:
        | '/platform/'
      views:
        | never
    }
    'src/pages/platform/admins.vue': {
      routes:
        | '/platform/admins'
      views:
        | never
    }
    'src/pages/platform/audit.vue': {
      routes:
        | '/platform/audit'
      views:
        | never
    }
    'src/pages/platform/companies/index.vue': {
      routes:
        | '/platform/companies/'
      views:
        | never
    }
    'src/pages/platform/companies/[id].vue': {
      routes:
        | '/platform/companies/[id]'
      views:
        | never
    }
    'src/pages/platform/plans.vue': {
      routes:
        | '/platform/plans'
      views:
        | never
    }
    'src/pages/print.vue': {
      routes:
        | '/print'
      views:
        | never
    }
    'src/pages/products/[[id]].vue': {
      routes:
        | '/products/[[id]]'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/qc-inspection/index.vue': {
      routes:
        | '/qc-inspection/'
      views:
        | never
    }
    'src/pages/qc-inspection/lots/[id].vue': {
      routes:
        | '/qc-inspection/lots/[id]'
      views:
        | never
    }
    'src/pages/qc-inspection/specifications/[id].vue': {
      routes:
        | '/qc-inspection/specifications/[id]'
      views:
        | never
    }
    'src/pages/qualityEvents/[[id]].vue': {
      routes:
        | '/qualityEvents/[[id]]'
      views:
        | never
    }
    'src/pages/qualityEvents/dashboard.vue': {
      routes:
        | '/qualityEvents/dashboard'
      views:
        | never
    }
    'src/pages/rca-templates.vue': {
      routes:
        | '/rca-templates'
      views:
        | never
    }
    'src/pages/records.vue': {
      routes:
        | '/records'
      views:
        | never
    }
    'src/pages/reset-esign-pin.vue': {
      routes:
        | '/reset-esign-pin'
      views:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
    }
    'src/pages/risk-assessment-templates.vue': {
      routes:
        | '/risk-assessment-templates'
      views:
        | never
    }
    'src/pages/roles/[[id]].vue': {
      routes:
        | '/roles/[[id]]'
      views:
        | never
    }
    'src/pages/security.vue': {
      routes:
        | '/security'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/signin.vue': {
      routes:
        | '/signin'
      views:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
    }
    'src/pages/sites.vue': {
      routes:
        | '/sites'
      views:
        | never
    }
    'src/pages/supplier/index.vue': {
      routes:
        | '/supplier/'
      views:
        | never
    }
    'src/pages/supplier/document-requests.vue': {
      routes:
        | '/supplier/document-requests'
      views:
        | never
    }
    'src/pages/supplier-document/[token].vue': {
      routes:
        | '/supplier-document/[token]'
      views:
        | never
    }
    'src/pages/suppliers/[[id]].vue': {
      routes:
        | '/suppliers/[[id]]'
      views:
        | never
    }
    'src/pages/support/[slug].vue': {
      routes:
        | '/support/[slug]'
      views:
        | never
    }
    'src/pages/support/ticket/[id].vue': {
      routes:
        | '/support/ticket/[id]'
      views:
        | never
    }
    'src/pages/task-instances.vue': {
      routes:
        | '/task-instances'
      views:
        | never
    }
    'src/pages/templates/[[id]].vue': {
      routes:
        | '/templates/[[id]]'
      views:
        | never
    }
    'src/pages/training-instances/[[id]].vue': {
      routes:
        | '/training-instances/[[id]]'
      views:
        | never
    }
    'src/pages/training-matrix.vue': {
      routes:
        | '/training-matrix'
      views:
        | never
    }
    'src/pages/training-verifications/[[id]].vue': {
      routes:
        | '/training-verifications/[[id]]'
      views:
        | never
    }
    'src/pages/trainings/[[id]].vue': {
      routes:
        | '/trainings/[[id]]'
      views:
        | never
    }
    'src/pages/users/[[id]].vue': {
      routes:
        | '/users/[[id]]'
      views:
        | never
    }
    'src/pages/workflow-instances/[[id]].vue': {
      routes:
        | '/workflow-instances/[[id]]'
      views:
        | never
    }
    'src/pages/workflow-templates/[[id]].vue': {
      routes:
        | '/workflow-templates/[[id]]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
