// TRN-J14 · Training content, material and assessment can be authored — and
// what the product does NOT require. OQ-02 TC-02-01 (URS-TRN-01).
//
// The gap this file closes, verbatim from the coverage matrix: "Passing score,
// material and assessment are not required at create." TRN-J9 already says so
// in prose — its header explains at length why it deliberately contains no
// REQUIRED_KEYS loop — but prose in a header is not a regression test. Nothing
// currently FAILS if a future change quietly starts requiring, or quietly stops
// defaulting, any of them. This file turns that documented design decision into
// an asserted one, and covers the positive half TC-02-01 actually asks for: that
// the three things CAN be authored, and survive to the published record.
//
// ── THE SHAPE OF THE REQUIREMENT, AND THE SHAPE OF THE PRODUCT ──────────────
// URS-TRN-01 is a CAPABILITY requirement — "Training content, material and
// assessment can be authored" — not a mandate. TC-02-01's steps ask the
// executor to author an assessment with a passing score and attach material.
// The product supports all of that, and requires none of it: a training starts
// as a bare DRAFT shell you flesh out afterwards, the same deliberate
// permissiveness as NC's draft route.
//
// Read from primary sources rather than inferred:
//
//   · `createTraining` (controllers/trainings.js:44-73) hand-checks ONE thing:
//         if (!title?.trim()) throw new BadRequestError('title is required')
//     and then supplies defaults for the rest — `passingScore: passingScore ?? 70`,
//     `maxAttempts: maxAttempts ?? 1`, `requireManagerVerification: … ?? true`,
//     `assessment: assessment ?? null`. There is no zod schema on the route.
//   · `Training.assessment` is `allowNull: false` with `defaultValue: []`, and
//     the controller passes the body through, so the default never applies and
//     a bare `{ title }` 400s at the MODEL layer, not the controller's. The
//     required surface is split across two layers and the route's own doc
//     comment mentions only the first — TRN-J9 found this the hard way.
//   · `activateTraining` (:116-125) publishes on ONE condition —
//     `status === 'DRAFT'`. No assessment check, no material check, no passing
//     score check. The only additional gate is the model's `beforeSave` hook,
//     which requires a `managerId` to reach ACTIVE.
//
// So the honest finding, asserted below rather than asserted around: **an empty
// training — no questions, no material, no manager verification — can be
// published and launched, and every assignee who submits scores 100.**
// `gradeAssessment` returns 100 for an empty assessment
// (shared/utils/trainingAssessment.js). That is pinned as a KNOWN DEFECT with
// its diagnosis, because a "trained and competent" record generated by a
// training that asked nothing is a Part-11 record with no substance behind it.
//
// Nothing here weakens a test to make it pass: the arms that assert acceptance
// assert the DEFAULT the product documents, and each is paired with the
// consequence it produces, so the record shows both what happens and why it
// matters.
//
// Measured 2026-09-23 against the live local stack (app-db + api :4000).
import { test, expect } from '../../video/fixtures/videoTest.js'
import { AUTH, USERS, COMPANY_ID, ESIGN_PIN, TRAINING } from '../fixtures/cast.js'
import { sql, sqlValue } from '../fixtures/db.js'

let seq = 0
function uniqueSuffix() {
  seq += 1
  return `${process.pid}-${seq}`
}

const ESIGN = { method: 'PIN', token: ESIGN_PIN }

/** Create a training over REST and return its row id (or null when refused). */
async function createTraining(ctx, body) {
  const res = await ctx.request.post('/api/v1/services/trainings', { data: body })
  const id = body.title ? sqlValue(`SELECT id FROM trainings WHERE title = '${body.title}' LIMIT 1`) : null
  return { res, id }
}

function dropTraining(id) {
  if (!id) return
  sql(`DELETE FROM training_document_links WHERE training_id = '${id}'`)
  sql(`DELETE FROM training_users WHERE training_id = '${id}'`)
  sql(`DELETE FROM training_roles WHERE training_id = '${id}'`)
  sql(`DELETE FROM trainings WHERE id = '${id}'`)
}

/** An EFFECTIVE document to attach as material. */
function seedDocument(tag) {
  const suffix = uniqueSuffix()
  const title = `E2E TRN-J14 ${tag} Doc ${suffix}`
  const out = sql(`
    WITH d AS (
      INSERT INTO documents (company_id, title, doc_number, created_at, updated_at)
      VALUES ('${COMPANY_ID}', '${title}', 'ETRNJ14-${suffix}', now(), now())
      RETURNING id
    ), v AS (
      INSERT INTO document_versions
        (company_id, document_id, version_major, version_minor, status_id, is_latest, created_at, updated_at)
      SELECT '${COMPANY_ID}', d.id, 1, 0, 'EFFECTIVE', true, now(), now() FROM d
      RETURNING id, document_id
    )
    SELECT (SELECT id FROM d), (SELECT id FROM v)
  `)
  const [id, versionId] = out.split('|')
  return { id, versionId, title }
}

function dropDocument(doc) {
  if (!doc?.id) return
  sql(`DELETE FROM document_versions WHERE document_id = '${doc.id}'`)
  sql(`DELETE FROM documents WHERE id = '${doc.id}'`)
}

test.describe('TRN-J14 · authoring completeness — what is required, and what is merely offered', () => {
  test.use({ storageState: AUTH.trainingAdmin })

  // ── The POSITIVE half TC-02-01 actually asks for ─────────────────────────
  test('TC-02-01 · content, material AND assessment are all authorable, and all survive to the published record', async ({
    browser,
  }) => {
    // The requirement is a capability claim, so the first duty of this file is
    // to show the capability exists — authored in ONE create call, the way the
    // authoring form posts it, and then read back from the database rather than
    // from the response echo (an endpoint that echoed its own input while
    // persisting nothing would otherwise pass).
    test.setTimeout(120_000)
    const ctx = await browser.newContext({ storageState: AUTH.trainingAdmin })
    const doc = seedDocument('authored')
    const title = `E2E TRN-J14 authored ${uniqueSuffix()}`
    const assessment = JSON.parse(
      sqlValue(`SELECT assessment::text FROM trainings WHERE id = '${TRAINING.id}'`),
    )
    let id = null

    try {
      const created = await createTraining(ctx, {
        title,
        description: 'Authored in full: instructions, linked material and a scored assessment.',
        instructions: 'Read the linked SOP, then answer both questions.',
        assessment,
        passingScore: 80,
        maxAttempts: 3,
        completionDueDays: 14,
        requireManagerVerification: true,
        managerId: USERS.trainingAdmin.id,
        documentIds: [doc.id],
        externalLinks: [{ title: 'Regulator guidance', url: 'https://example.invalid/guidance', type: 'LINK' }],
      })
      id = created.id
      expect(created.res.ok(), `a fully-authored training is accepted — ${await created.res.text()}`).toBe(true)
      expect(id, 'the training row exists').toBeTruthy()

      // CONTENT — the authored scalars, from the row.
      const row = sql(
        `SELECT passing_score, max_attempts, completion_due_days, require_manager_verification, manager_id, instructions
           FROM trainings WHERE id = '${id}'`,
      ).split('|')
      expect(Number(row[0]), 'the authored passing score is stored — not the 70 default').toBe(80)
      expect(Number(row[1]), 'the authored attempt ceiling is stored — not the 1 default').toBe(3)
      expect(Number(row[2]), 'the authored completion window is stored').toBe(14)
      expect(row[3], 'manager verification is stored').toBe('t')
      expect(row[4], 'the training manager is stored').toBe(USERS.trainingAdmin.id)
      expect(row[5]).toContain('Read the linked SOP')

      // ASSESSMENT — stored as authored, question for question.
      expect(
        Number(sqlValue(`SELECT jsonb_array_length(assessment) FROM trainings WHERE id = '${id}'`)),
        'both authored questions are stored',
      ).toBe(assessment.length)

      // MATERIAL — both kinds. A document link and an external link are
      // separate tables, and TC-02-01 asks for material generally, so both are
      // evidenced rather than one standing in for the other.
      expect(
        sqlValue(
          `SELECT count(*) FROM training_document_links
            WHERE training_id = '${id}' AND document_id = '${doc.id}' AND deleted_at IS NULL`,
        ),
        'the linked document is attached as material',
      ).toBe('1')
      expect(
        Number(
          sqlValue(
            `SELECT count(*) FROM training_external_links WHERE training_id = '${id}' AND deleted_at IS NULL`,
          ),
        ),
        'the external link is attached as material too',
      ).toBeGreaterThanOrEqual(1)

      // …and it publishes, which is what makes it a training rather than a draft.
      const activated = await ctx.request.post(`/api/v1/services/trainings/${id}/activate`)
      expect(activated.ok(), `a fully-authored training publishes — ${await activated.text()}`).toBe(true)
      expect(sqlValue(`SELECT status FROM trainings WHERE id = '${id}'`)).toBe('ACTIVE')
    } finally {
      dropTraining(id)
      dropDocument(doc)
      await ctx.close()
    }
  })

  // ── The NEGATIVE half: what is NOT required ──────────────────────────────
  test('TC-02-01 · a PASSING SCORE is not required at create — the server silently defaults it to 70', async ({
    browser,
  }) => {
    // Asserted as the default it is, not as a refusal. A test expecting a 400
    // here would be wrong-while-red against a documented design decision; a
    // test asserting only "201" would miss the part that matters, which is that
    // a number the author never chose is now the bar every learner is judged
    // against.
    test.setTimeout(90_000)
    const ctx = await browser.newContext({ storageState: AUTH.trainingAdmin })
    const title = `E2E TRN-J14 nopass ${uniqueSuffix()}`
    let id = null

    try {
      const created = await createTraining(ctx, { title, assessment: [] })
      id = created.id
      expect(
        created.res.ok(),
        `omitting passingScore is accepted by design — ${await created.res.text()}`,
      ).toBe(true)
      expect(
        Number(sqlValue(`SELECT passing_score FROM trainings WHERE id = '${id}'`)),
        'and a passing score of 70 is chosen FOR the author, who was never asked',
      ).toBe(70)
      // Same story for the attempt ceiling, which TRN-J12 then enforces.
      expect(
        Number(sqlValue(`SELECT max_attempts FROM trainings WHERE id = '${id}'`)),
        'maxAttempts likewise defaults to 1 rather than being required',
      ).toBe(1)
    } finally {
      dropTraining(id)
      await ctx.close()
    }
  })

  test('TC-02-01 · MATERIAL is not required at create — a training with nothing to read is accepted', async ({
    browser,
  }) => {
    test.setTimeout(90_000)
    const ctx = await browser.newContext({ storageState: AUTH.trainingAdmin })
    const title = `E2E TRN-J14 nomaterial ${uniqueSuffix()}`
    let id = null

    try {
      const created = await createTraining(ctx, { title, assessment: [] })
      id = created.id
      expect(created.res.ok(), `omitting material is accepted by design`).toBe(true)
      expect(
        sqlValue(`SELECT count(*) FROM training_document_links WHERE training_id = '${id}'`),
        'no document material',
      ).toBe('0')
      expect(
        sqlValue(`SELECT count(*) FROM training_external_links WHERE training_id = '${id}'`),
        'no external material either',
      ).toBe('0')
      // Consequence, stated rather than implied: the material-review gate
      // TRN-J11 exists to test is VACUOUS on a training like this —
      // `allMaterialViewed` is `[].every(...)`, which is true.
      expect(
        sqlValue(`SELECT status FROM trainings WHERE id = '${id}'`),
        'and it is a perfectly valid DRAFT training',
      ).toBe('DRAFT')
    } finally {
      dropTraining(id)
      await ctx.close()
    }
  })

  test('TC-02-01 · an ASSESSMENT is not required — but the key must be PRESENT, and that split is the trap', async ({
    browser,
  }) => {
    // The distinction TRN-J9's control test found the hard way, pinned here as
    // its own arm because the two failure modes look identical from the outside
    // and mean opposite things:
    //
    //   · assessment ABSENT  → 400, from the MODEL's `allowNull: false`.
    //     Reads like "an assessment is required" and is not: it is a
    //     null-vs-default accident, because the controller passes
    //     `assessment ?? null` through and the column's `defaultValue: []`
    //     therefore never applies.
    //   · assessment EMPTY ARRAY → 201. A training with zero questions is a
    //     first-class, publishable record.
    test.setTimeout(90_000)
    const ctx = await browser.newContext({ storageState: AUTH.trainingAdmin })
    const absentTitle = `E2E TRN-J14 noassess ${uniqueSuffix()}`
    const emptyTitle = `E2E TRN-J14 emptyassess ${uniqueSuffix()}`
    let emptyId = null

    try {
      const before = Number(sqlValue(`SELECT count(*) FROM trainings`))

      const absent = await ctx.request.post('/api/v1/services/trainings', {
        data: { title: absentTitle },
      })
      expect(
        absent.status(),
        'omitting the key entirely 400s — at the MODEL layer, not the controller',
      ).toBe(400)
      expect((await absent.text()).toLowerCase()).toContain('assessment')
      expect(Number(sqlValue(`SELECT count(*) FROM trainings`)), 'nothing was written').toBe(before)

      const empty = await createTraining(ctx, { title: emptyTitle, assessment: [] })
      emptyId = empty.id
      expect(
        empty.res.ok(),
        'an EMPTY assessment is accepted — zero questions is a valid authored state',
      ).toBe(true)
      expect(
        Number(sqlValue(`SELECT jsonb_array_length(assessment) FROM trainings WHERE id = '${emptyId}'`)),
        'and it is stored as the empty array, not coerced into anything',
      ).toBe(0)
    } finally {
      dropTraining(emptyId)
      sql(`DELETE FROM trainings WHERE title = '${absentTitle}'`)
      await ctx.close()
    }
  })

  test('KNOWN DEFECT TRN-D18 · a question-less training PUBLISHES and grades every learner 100', async ({
    browser,
  }) => {
    // The consequence of the three arms above, taken together, and the reason
    // they are worth asserting rather than leaving as a header note.
    //
    // `activateTraining` gates on `status === 'DRAFT'` alone — no completeness
    // check of any kind — and `gradeAssessment` returns **100 for an empty
    // assessment**. So a training that asks nothing, offers nothing to read and
    // was never given a passing score by its author can be published, launched,
    // and will mint a signed, score-100, "competent" record for a learner who
    // answered no questions.
    //
    // Pinned AS IT BEHAVES, per this suite's convention for open defects
    // (e2e/README.md, IL-D1): the arms assert the real 200/100/VERIFIED, so the
    // suite stays green and goes RED the day a completeness gate lands at
    // activate — which is the signal to flip it into a refusal test.
    //
    // NOT inverted into a failing-by-design test like TRN-J10/J11, and the
    // difference is deliberate: those two assert a SECURITY control the
    // protocol explicitly requires (a published training must not be editable;
    // a completion must not be signable unread). "A training must contain
    // questions" is not stated as a requirement anywhere in URS-TRN-01 or
    // TC-02-01 — it is an authoring-quality gap. Asserting it as a required
    // refusal would be inventing a requirement.
    test.setTimeout(150_000)
    const ctx = await browser.newContext({ storageState: AUTH.trainingAdmin })
    const title = `E2E TRN-J14 hollow ${uniqueSuffix()}`
    let id = null
    let instanceId = null

    try {
      const created = await createTraining(ctx, {
        title,
        assessment: [],
        requireManagerVerification: false,
        managerId: USERS.trainingAdmin.id,
      })
      id = created.id
      expect(created.res.ok()).toBe(true)

      // It publishes. No completeness gate exists to stop it.
      const activated = await ctx.request.post(`/api/v1/services/trainings/${id}/activate`)
      expect(
        activated.ok(),
        'KNOWN DEFECT TRN-D18: a training with no questions and no material publishes',
      ).toBe(true)
      expect(sqlValue(`SELECT status FROM trainings WHERE id = '${id}'`)).toBe('ACTIVE')

      // It launches.
      const launched = await ctx.request.post(`/api/v1/services/trainings/${id}/launch`, {
        data: { userIds: [USERS.learner.id], reason: 'TRN-J14 hollow training' },
      })
      expect(launched.status(), `launch — ${await launched.text()}`).toBe(201)
      instanceId = (await launched.json())?.trainingInstance?.id
      expect(instanceId).toBeTruthy()

      // And it grades a learner who answered nothing at 100.
      const learnerCtx = await browser.newContext({ storageState: AUTH.learner })
      const submitted = await learnerCtx.request.post(
        `/api/v1/services/trainingInstances/${instanceId}/submit`,
        { data: { answers: {}, esign: ESIGN } },
      )
      expect(
        submitted.ok(),
        `the submit is accepted — ${await submitted.text().catch(() => '')}`,
      ).toBe(true)
      const body = await submitted.json()
      expect(
        body.score,
        'KNOWN DEFECT TRN-D18: an empty assessment grades 100 — gradeAssessment’s empty case',
      ).toBe(100)
      expect(body.passed, 'and therefore passes, against a passing score nobody chose').toBe(true)
      await learnerCtx.close()

      const assignee = sql(
        `SELECT status, score, signed_at IS NOT NULL FROM training_assignees
          WHERE training_instance_id = '${instanceId}' AND user_id = '${USERS.learner.id}'`,
      ).split('|')
      // VERIFIED via the auto-verify shortcut, since requireManagerVerification
      // is false — the same edge TRN-J11's control documents.
      expect(assignee[0]).toMatch(/^(COMPLETED|VERIFIED)$/)
      expect(Number(assignee[1]), 'a signed competency record scoring 100').toBe(100)
      expect(
        assignee[2],
        'and it IS e-signed — the Part-11 record is real; only its substance is not',
      ).toBe('t')
    } finally {
      if (instanceId) {
        sql(`DELETE FROM task_instances WHERE entity_id IN (
               SELECT id FROM training_assignees WHERE training_instance_id = '${instanceId}')`)
        sql(`DELETE FROM training_assignees WHERE training_instance_id = '${instanceId}'`)
        sql(`DELETE FROM training_assessment_keys WHERE training_instance_id = '${instanceId}'`)
        sql(`DELETE FROM training_instances WHERE id = '${instanceId}'`)
      }
      dropTraining(id)
      await ctx.close()
    }
  })

  test('publishing without a Training Manager IS refused — the one completeness gate that exists', async ({
    browser,
  }) => {
    // The counterweight, and the reason the defect above is a gap rather than a
    // philosophy. The product DOES have a publish-time completeness gate; it
    // just guards exactly one field. `Training.beforeSave` throws "A Training
    // Manager is required to publish a training" when status reaches ACTIVE
    // with no managerId.
    //
    // Worth pinning here because it proves the arms above are not vacuous: if
    // `activate` refused everything, "a hollow training publishes" would be
    // untrue and this test would be the one to say so.
    test.setTimeout(90_000)
    const ctx = await browser.newContext({ storageState: AUTH.trainingAdmin })
    const title = `E2E TRN-J14 nomanager ${uniqueSuffix()}`
    let id = null

    try {
      const created = await createTraining(ctx, { title, assessment: [] })
      id = created.id
      expect(created.res.ok(), 'a manager is NOT required at create').toBe(true)
      // `sqlValue` reads psql's tuples-only stdout, where a NULL column and an
      // absent row are both empty-ish but not the same value ('' vs null), so
      // ask the database for the boolean rather than pattern-matching stdout.
      expect(
        sqlValue(`SELECT manager_id IS NULL FROM trainings WHERE id = '${id}'`),
        'the training was created with no manager',
      ).toBe('t')

      const activated = await ctx.request.post(`/api/v1/services/trainings/${id}/activate`)
      expect(
        activated.ok(),
        'but it IS required to publish — the model hook refuses',
      ).toBe(false)
      expect(
        sqlValue(`SELECT status FROM trainings WHERE id = '${id}'`),
        'and the training stayed DRAFT',
      ).toBe('DRAFT')

      // KNOWN DEFECT D16 (already pinned by TRN-J10): the hook throws a plain
      // Error, so this arrives as a bare 500 rather than a 400. Asserted as it
      // behaves so this file agrees with J10 rather than contradicting it.
      expect(
        activated.status(),
        'KNOWN DEFECT D16: the refusal is a 500, not a 400 — a plain Error from the model hook',
      ).toBe(500)
    } finally {
      dropTraining(id)
      await ctx.close()
    }
  })
})
