// The marketing shot list — one entry per product screen worth showing.
//
// Every entry is a REAL route in the running app, opened as a real persona
// against the Nordic demo tenant. Nothing here fabricates UI: `actions` only
// click tabs / open dialogs a user would open, and `focus` only names which
// on-screen card the zoomed variant crops to.
//
//   id        stable asset id (file names derive from it)
//   module    marketing module folder
//   feature   what the screen demonstrates
//   url       route; with `sql` it is only the fallback/base route for reports
//   sql       read-only SELECT returning the route from live data (wins over url);
//             no row → logged blocked with the `blocked` reason, so the shot
//             captures by itself once the data is seeded
//   actions   [{ tab }, { click }, { clickText }, { fill, value }, { press },
//             { scrollTo }, { wait }] run after load — fill only types into search
//             boxes; capture.mjs aborts every write request regardless
//   focus     text of a heading/label inside the card to zoom into
//   focusSel  CSS selector instead of focus text
//   hero      also build a hero composition
//   blocked   reason the screen cannot be captured from existing demo data;
//             the shot is logged as blocked and not opened
//   slots     qms-marketing app/content/media.ts slot ids this could fill
//   page      recommended marketing page + section
export const NORDIC = "(SELECT id FROM companies WHERE lower(code) = 'nordic')"

export const SHOTS = [
  // ── Overview ────────────────────────────────────────────────────────────
  { id: 'overview-dashboard', module: 'overview', feature: 'Quality dashboard — open NCs, CAPAs, tasks and audits at a glance', url: '/dashboard', focus: 'CAPAs Due', hero: true, slots: ['about.hero', 'industries.medical-devices.hero'], page: 'Home / About — hero' },
  { id: 'overview-my-tasks', module: 'overview', feature: 'My Tasks inbox across every module', url: '/task-instances', slots: ['workflows.accountability'], page: 'Platform — task inbox' },

  // ── Document Control ────────────────────────────────────────────────────
  { id: 'document-control-library', module: 'document-control', feature: 'Controlled document library', url: '/documents', page: 'Document Control — overview' },
  { id: 'document-control-sop-effective', module: 'document-control', feature: 'Effective SOP with numbered sections and properties rail', url: '/documents/da100001-1111-4000-8000-000000000002', actions: [{ click: 'button:has-text("Version:")' }, { click: '[id^="headlessui-popover-panel"] button:has-text("Version 3.0")' }], focus: 'Properties', hero: true, page: 'Document Control — hero' },
  { id: 'document-control-version-history', module: 'document-control', feature: 'Version selector: effective, superseded and draft versions', url: '/documents/da100001-1111-4000-8000-000000000002', actions: [{ click: 'button:has-text("Version:")' }], focusSel: '[id^="headlessui-popover-panel"]', slots: ['documents.versionControl'], page: 'Document Control — version control' },
  { id: 'document-control-change-control', module: 'document-control', feature: 'Document change-control tab: reason, change type and summary of a major revision', url: '/documents/da100001-1111-4000-8000-000000000001', actions: [{ tab: 'Change Control' }], page: 'Document Control — change control' },
  { id: 'document-control-training-link', module: 'document-control', feature: 'Training linked to a controlled document', url: '/documents', sql: `SELECT '/documents/' || d.id FROM documents d JOIN document_versions dv ON dv.document_id = d.id AND dv.is_latest AND dv.deleted_at IS NULL WHERE d.company_id = ${NORDIC} AND d.deleted_at IS NULL AND dv.status_id = 'EFFECTIVE' AND ((dv.training_config->>'enabled')::boolean OR EXISTS (SELECT 1 FROM training_document_links l WHERE l.document_id = d.id AND l.deleted_at IS NULL)) ORDER BY d.created_at LIMIT 1`, actions: [{ tab: 'Training' }], blocked: 'no Nordic document has training configured (every document_versions.training_config is off/null and training_document_links is empty); opening the Training tab on an editable draft also autosaves a default training_config', page: 'Document Control — training on release' },
  { id: 'document-control-create', module: 'document-control', feature: 'New document from a template', url: '/documents/create', page: 'Document Control — authoring' },
  { id: 'document-control-print-view', module: 'document-control', feature: 'Controlled print / PDF view of an effective SOP with status banner and document block', url: '/print?module=Document&id=da100001-1111-4000-8000-000000000002&versionId=da110001-1111-4000-8000-000000000005', page: 'Document Control — controlled copies' },

  // ── Nonconformance ──────────────────────────────────────────────────────
  { id: 'nonconformance-register', module: 'nonconformance', feature: 'Nonconformance register', url: '/nonconformances', page: 'Nonconformance — overview' },
  { id: 'nonconformance-closed-disposition', module: 'nonconformance', feature: 'Closed NC with severity, root cause, disposition and cost', url: '/nonconformances/db100001-1111-4000-8000-000000000080', focus: 'Disposition', hero: true, slots: ['capa.nonconformance'], page: 'Nonconformance — investigation & disposition' },
  { id: 'nonconformance-supplier-facing', module: 'nonconformance', feature: 'Supplier-facing nonconformance', url: '/nonconformances/db100001-1111-4000-8000-000000000049', focus: 'Product impact', slots: ['nonconformance.supplier'], page: 'Nonconformance — supplier NCs' },
  { id: 'nonconformance-create', module: 'nonconformance', feature: 'Raise a nonconformance', url: '/nonconformances/create', page: 'Nonconformance — raise' },
  { id: 'nonconformance-approve-close', module: 'nonconformance', feature: 'Approve & Close dialog on an open NC', url: '/nonconformances', sql: `SELECT '/nonconformances/' || n.id FROM nonconformances n WHERE n.company_id = ${NORDIC} AND n.deleted_at IS NULL AND n.status_id = 'OPEN' AND n.disposition_type_id IS NOT NULL AND coalesce(trim(n.disposition_notes), '') <> '' AND n.capa_required IS NOT TRUE AND n.title !~* '(email|test|e2e|firehose)' AND NOT EXISTS (SELECT 1 FROM workflow_instances w JOIN workflow_instance_steps st ON st.workflow_instance_id = w.id WHERE w.resource_id = n.id AND w.deleted_at IS NULL AND st.deleted_at IS NULL AND st.status_id IN ('PENDING', 'IN_PROGRESS')) ORDER BY n.nc_number LIMIT 1`, actions: [{ click: 'button:has-text("Approve & Close"):not([disabled])' }], focusSel: '[id^="headlessui-dialog-panel"]', blocked: 'Approve & Close is disabled on every OPEN Nordic NC: no NC has disposition_notes (required before marking complete), so the dialog cannot be opened without editing data', page: 'Nonconformance — closure' },

  // ── CAPA ────────────────────────────────────────────────────────────────
  { id: 'capa-register', module: 'capa', feature: 'CAPA register', url: '/capas', page: 'CAPA — overview' },
  { id: 'capa-closed-effectiveness', module: 'capa', feature: 'Closed CAPA with effectiveness verification', url: '/capas/db200001-1111-4000-8000-000000000133', focus: 'CAPA Details', hero: true, slots: ['capa.effectiveness'], page: 'CAPA — effectiveness' },
  { id: 'capa-workflow-tab', module: 'capa', feature: 'CAPA workflow section', url: '/capas', sql: `SELECT '/capas/' || c.id FROM capas c JOIN workflow_instances w ON w.resource_id = c.id AND w.resource_type = 'Capa' AND w.deleted_at IS NULL WHERE c.company_id = ${NORDIC} AND c.deleted_at IS NULL AND c.title !~* '(email|test|e2e|firehose)' ORDER BY (w.status_id = 'IN_PROGRESS') DESC, w.updated_at DESC LIMIT 1`, actions: [{ click: 'main a:text-is("Workflow")' }], focusSel: '[id^="section-workflow"]', blocked: 'no Nordic CAPA has a workflow instance (workflow_instances holds only Complaint + one EMAIL-TEST NC); the CAPA "Workflow" tab is an in-page anchor to a card reading "No workflow selected yet". The CAPA workflow TEMPLATE is covered by workflows-builder', page: 'CAPA — workflow' },
  { id: 'capa-create', module: 'capa', feature: 'Create CAPA form', url: '/capas/create', page: 'CAPA — raise' },

  // ── Change Control ──────────────────────────────────────────────────────
  { id: 'change-control-register', module: 'change-management', feature: 'Change request register', url: '/change-requests', page: 'Change Control — overview' },
  { id: 'change-control-request-detail', module: 'change-management', feature: 'Change request with reason, justification and linked records', url: '/change-requests/da500001-1111-4000-8000-000000000001', focus: 'Change Request Details', slots: ['change-control.affected', 'industries.medical-devices.dhf'], page: 'Change Control — affected items' },
  { id: 'change-control-create', module: 'change-management', feature: 'New change request', url: '/change-requests/create', page: 'Change Control — raise' },

  // ── Quality Events & Complaints ─────────────────────────────────────────
  { id: 'quality-events-register', module: 'quality-events', feature: 'Quality event register', url: '/qualityEvents', page: 'Quality Events — overview' },
  { id: 'quality-events-record', module: 'quality-events', feature: 'Quality event overview', url: '/qualityEvents/da920001-1111-4000-8000-000000000003', page: 'Quality Events — record' },
  { id: 'quality-events-escalations', module: 'quality-events', feature: 'Quality event escalations tab', url: '/qualityEvents', sql: `SELECT '/qualityEvents/' || q.id FROM quality_events q WHERE q.company_id = ${NORDIC} AND q.deleted_at IS NULL AND q.status_id <> 'DRAFT' AND EXISTS (SELECT 1 FROM record_links r WHERE r.from_type = 'QualityEvent' AND r.from_id = q.id AND r.deleted_at IS NULL) ORDER BY q.event_number LIMIT 1`, actions: [{ tab: 'Escalations' }], blocked: 'no Nordic quality event has been escalated (record_links has no QualityEvent rows) — the tab only shows "This event has not been escalated"', slots: ['quality-events.escalation'], page: 'Quality Events — escalation' },
  { id: 'complaints-register', module: 'complaints', feature: 'Quality complaint register', url: '/complaints', page: 'Complaints — overview' },
  { id: 'complaints-qa-review', module: 'complaints', feature: 'Complaint QA review with assessment', url: '/complaints/daf20001-1111-4000-8000-000000000001', hero: true, slots: ['complaints.hero', 'industries.medical-devices.complaints'], page: 'Complaints — hero' },
  { id: 'complaints-escalated-to-nc', module: 'complaints', feature: 'Complaint escalated into a nonconformance', url: '/complaints/daf20001-1111-4000-8000-000000000001', actions: [{ tab: 'Escalations' }], slots: ['complaints.convert'], page: 'Complaints — escalation to NC' },
  { id: 'complaints-esignature', module: 'complaints', feature: 'E-signature PIN challenge when approving a workflow step (opened, never signed)', url: '/complaints/daf20001-1111-4000-8000-000000000006', actions: [{ click: 'button:has-text("on behalf of")' }], focusSel: '[id^="headlessui-dialog-panel"]', slots: ['product.cap.e-signatures'], page: 'Platform — e-signatures' },
  { id: 'complaints-ai-assistant', module: 'complaints', feature: 'Ask AI assistant panel with the complaint as context', url: '/complaints', sql: `SELECT '/complaints/daf20001-1111-4000-8000-000000000001' WHERE EXISTS (SELECT 1 FROM company_ai_profile a WHERE a.company_id = ${NORDIC} AND a.enabled)`, actions: [{ click: 'button:has-text("Ask AI")' }, { wait: 1500 }], blocked: 'the Nordic tenant has the AI add-on off (/v1/auth/session aiEnabled=false), so ChatPanel is not mounted — the Ask AI button renders but opens nothing; document AI buttons (Draft with AI / Summarize / What changed) are hidden', slots: ['ai.trust'], page: 'AI — assistant' },
  { id: 'customer-complaints-queue', module: 'complaints', feature: 'Customer support queue', url: '/customer-complaints', page: 'Complaints — support desk' },
  { id: 'customer-complaints-ticket', module: 'complaints', feature: 'Customer ticket with public reply and internal note', url: '/customer-complaints/d7000001-1111-4000-8000-000000000001', focus: 'Ticket information', page: 'Complaints — support ticket' },

  // ── Audits ──────────────────────────────────────────────────────────────
  { id: 'audits-insights', module: 'audits', feature: 'Audit insights', url: '/audits?tab=insights', page: 'Audits — overview' },
  { id: 'audits-calendar', module: 'audits', feature: 'Audit schedule calendar', url: '/audits?tab=calendar', page: 'Audits — schedule' },
  { id: 'audits-execution-findings', module: 'audits', feature: 'Audit with its findings', url: '/audits/instances/db600001-1111-4000-8000-000000000013', actions: [{ tab: /^Findings/ }], hero: true, slots: ['audits.findings'], page: 'Audits — findings' },
  { id: 'audits-finding-linked-nc', module: 'audits', feature: 'Audit finding that raised a nonconformance', url: '/audits/instances', sql: `SELECT '/audits/instances/' || f.audit_instance_id FROM audit_findings f WHERE f.company_id = ${NORDIC} AND f.deleted_at IS NULL AND f.spawned_nc_id IS NOT NULL ORDER BY f.created_at LIMIT 1`, actions: [{ tab: /^Findings/ }], blocked: 'no Nordic audit finding has spawned_nc_id (or spawned_capa_id) set', page: 'Audits — findings to NC' },
  { id: 'audits-requirements', module: 'audits', feature: 'Audit requirements checklist', url: '/audits/instances', sql: `SELECT '/audits/instances/' || ai.id FROM audit_instances ai WHERE ai.company_id = ${NORDIC} AND ai.deleted_at IS NULL AND EXISTS (SELECT 1 FROM audit_requirement_responses r WHERE r.audit_instance_id = ai.id AND r.deleted_at IS NULL) ORDER BY (SELECT count(*) FROM audit_requirement_responses r WHERE r.audit_instance_id = ai.id) DESC LIMIT 1`, actions: [{ tab: /^Requirements/ }], blocked: 'Nordic has no audit standard versions or requirements (audit_standard_versions, audit_requirements and audit_requirement_responses are all empty for Nordic) — every audit shows 0 clauses', slots: ['audits.walkthrough'], page: 'Audits — walkthrough' },
  { id: 'audits-reports', module: 'audits', feature: 'Final auditor report issued on a supplier qualification audit', url: '/auditee/d5000001-1111-4000-8000-000000000002', actions: [{ click: 'main [role="tab"]:has-text("Reports"), main button:has-text("Reports")' }], page: 'Audits — report' },
  { id: 'audits-standard', module: 'audits', feature: 'Audit standard with requirements', url: '/audits/standards', sql: `SELECT '/audits/standards/' || s.id FROM audit_standards s WHERE s.company_id = ${NORDIC} AND s.deleted_at IS NULL AND EXISTS (SELECT 1 FROM audit_standard_versions v JOIN audit_requirements q ON q.audit_standard_version_id = v.id WHERE v.audit_standard_id = s.id AND q.deleted_at IS NULL) ORDER BY s.code LIMIT 1`, focus: 'Requirements', blocked: 'none of the 3 Nordic audit standards has a version or any requirements — the page shows "No version yet — try creating a new draft"', page: 'Audits — standards' },
  { id: 'audits-program', module: 'audits', feature: 'Audit programme schedule and auditor pool', url: '/audits/programs/da620001-1111-4000-8000-000000000004', focus: 'Schedule', page: 'Audits — programmes' },
  { id: 'audits-readiness', module: 'audits', feature: 'Audit readiness', url: '/audits?tab=readiness', page: 'Audits — readiness' },
  { id: 'audits-auditee-portal', module: 'audits', feature: 'Auditee view of an ISO 9001 surveillance audit with the certification body', url: '/auditee/d5000001-1111-4000-8000-000000000003', page: 'Audits — auditee' },

  // ── Training ────────────────────────────────────────────────────────────
  { id: 'training-catalogue', module: 'training', feature: 'Training catalogue', url: '/trainings', page: 'Training — overview' },
  { id: 'training-course-material', module: 'training', feature: 'Training course material', url: '/trainings/da200001-1111-4000-8000-000000000002', actions: [{ tab: 'Material' }], page: 'Training — course' },
  { id: 'training-assessment', module: 'training', feature: 'Training assessment questions', url: '/trainings', sql: `SELECT '/trainings/' || t.id FROM trainings t WHERE t.company_id = ${NORDIC} AND t.deleted_at IS NULL AND t.status = 'ACTIVE' AND t.title !~* '(email|test|e2e)' AND EXISTS (SELECT 1 FROM jsonb_array_elements(coalesce(t.assessment, '[]'::jsonb)) q WHERE coalesce(q->>'text', '') <> '') ORDER BY jsonb_array_length(t.assessment) DESC LIMIT 1`, actions: [{ tab: 'Assessment' }], blocked: 'every seeded Nordic training stores its question under "prompt" but TrainingAssessmentEditor renders q.text, so each question shows "(empty question)" above its answer options', slots: ['training.quizGeneration'], page: 'Training — assessment' },
  { id: 'training-instance-progress', module: 'training', feature: 'Assignee progress on a training instance', url: '/training-instances/dbd10001-1111-4000-8000-000000000043', focus: 'Assignee Progress', page: 'Training — progress' },
  { id: 'training-verifications', module: 'training', feature: 'Manager competency verifications', url: '/training-verifications', slots: ['training.verification'], page: 'Training — verification' },
  { id: 'training-curriculum', module: 'training', feature: 'Role-based curriculum', url: '/training-curriculum', slots: ['training.autoAssignment'], page: 'Training — auto-assignment' },
  { id: 'training-matrix', module: 'training', feature: 'Training matrix report: every assignment by user, status and completion', url: '/training-reports', page: 'Training — matrix' },

  // ── QC / Inspections / Equipment / Items ────────────────────────────────
  { id: 'qc-inspection-lots', module: 'qc-inspection', feature: 'Inspection lot queue', url: '/qc-inspection?tab=lots', page: 'QC Inspection — overview' },
  { id: 'qc-inspection-lot-results', module: 'qc-inspection', feature: 'Inspection lot with results', url: '/qc-inspection/lots', sql: `SELECT '/qc-inspection/lots/' || l.id FROM inspection_lots l WHERE l.company_id = ${NORDIC} AND l.deleted_at IS NULL AND l.spec_snapshot IS NOT NULL AND l.lot_number !~* '(email|test|e2e)' AND EXISTS (SELECT 1 FROM inspection_results r WHERE r.inspection_lot_id = l.id AND r.deleted_at IS NULL) ORDER BY l.lot_number DESC LIMIT 1`, focus: 'Results', blocked: 'no Nordic lot renders results: all 211 lots that have inspection_results have spec_snapshot NULL, so the Results card shows "No specification linked to this lot" (the only lot with a spec snapshot is EMAIL-TEST-LOT-PASS, with 0 results)', page: 'QC Inspection — results' },
  { id: 'qc-inspection-specifications', module: 'qc-inspection', feature: 'Specifications library', url: '/qc-inspection?tab=specifications', page: 'QC Inspection — specifications' },
  { id: 'qc-inspection-sampling-plans', module: 'qc-inspection', feature: 'Sampling plans', url: '/qc-inspection?tab=sampling-plans', page: 'QC Inspection — sampling' },
  { id: 'qc-inspection-retain-samples', module: 'qc-inspection', feature: 'Retain samples', url: '/qc-inspection?tab=retain-samples', page: 'QC Inspection — retain samples' },
  { id: 'qc-inspection-line-clearance', module: 'qc-inspection', feature: 'Line clearance', url: '/qc-inspection?tab=line-clearance', sql: `SELECT '/qc-inspection?tab=line-clearance' WHERE EXISTS (SELECT 1 FROM form_templates t WHERE t.company_id = ${NORDIC} AND t.internal_name = 'QC_LINE_CLEARANCE' AND t.deleted_at IS NULL)`, blocked: 'Nordic has no QC_LINE_CLEARANCE form template, so the tab shows the "No line clearance checklist… run db:reseed" setup banner', page: 'QC Inspection — line clearance' },
  { id: 'inspections-logs-register', module: 'inspections-logs', feature: 'Log entries register', url: '/inspections-logs?tab=logs', page: 'Inspections & Logs — overview' },
  { id: 'inspections-logs-log-books', module: 'inspections-logs', feature: 'Log books', url: '/inspections-logs?tab=log-books', page: 'Inspections & Logs — log books' },
  { id: 'equipment-register', module: 'equipment-calibration', feature: 'Equipment register with calibration and PM due dates', url: '/equipment', hero: true, page: 'Equipment & Calibration — overview' },
  { id: 'equipment-record-calibration', module: 'equipment-calibration', feature: 'Record a calibration', url: '/equipment', actions: [{ click: 'button:has-text("Record calibration")' }], focusSel: '[id^="headlessui-dialog-panel"]', slots: ['product.cap.equipment-calibration'], page: 'Equipment & Calibration — capture' },
  { id: 'item-master-detail', module: 'item-master', feature: 'Item with its specifications', url: '/products/d8000001-1111-4000-8000-000000000001', actions: [{ tab: 'Specifications' }], page: 'Item Master — specifications' },

  // ── Suppliers ───────────────────────────────────────────────────────────
  { id: 'suppliers-register', module: 'suppliers', feature: 'Supplier register with risk level and status', url: '/suppliers', slots: ['suppliers.register', 'product.cap.supplier-management'], page: 'Suppliers — register' },
  { id: 'suppliers-overview', module: 'suppliers', feature: 'Supplier record: risk profile, audit findings, contacts', url: '/suppliers/da800001-1111-4000-8000-000000000003', focus: 'Risk Profile', hero: true, slots: ['suppliers.hero'], page: 'Suppliers — hero' },
  { id: 'suppliers-quality-records', module: 'suppliers', feature: 'Supplier quality records', url: '/suppliers/da800001-1111-4000-8000-000000000003', actions: [{ tab: 'Quality Records' }], page: 'Suppliers — quality records' },
  { id: 'suppliers-documents', module: 'suppliers', feature: 'Supplier documents and certificates', url: '/suppliers/d6000001-1111-4000-8000-000000000001', actions: [{ tab: 'Documents' }], page: 'Suppliers — documents' },
  { id: 'suppliers-evaluations', module: 'suppliers', feature: 'Supplier evaluations', url: '/suppliers', sql: `SELECT '/suppliers/' || r.supplier_id FROM records r WHERE r.company_id = ${NORDIC} AND r.supplier_id IS NOT NULL AND r.deleted_at IS NULL GROUP BY r.supplier_id ORDER BY count(*) DESC LIMIT 1`, actions: [{ tab: 'Evaluations' }], blocked: 'no Nordic supplier has an evaluation (the tab lists App Builder records with supplier_id set; there are none)', page: 'Suppliers — evaluations' },
  { id: 'supplier-portal-home', module: 'suppliers', persona: 'supplier', feature: 'Supplier portal as the supplier sees it', url: '/supplier', slots: ['suppliers.portal', 'product.cap.supplier-portal'], page: 'Suppliers — portal' },
  { id: 'supplier-portal-document-requests', module: 'suppliers', persona: 'supplier', feature: 'Supplier portal document requests', url: '/supplier/document-requests', slots: ['suppliers.documentRequests'], page: 'Suppliers — document requests' },

  // ── Analytics ───────────────────────────────────────────────────────────
  { id: 'analytics-quality-dashboard', module: 'analytics', feature: 'Quality analytics dashboard', url: '/analytics/dashboards/daa00001-1111-4000-8000-0000000000aa', focus: 'Audit findings by department', hero: true, page: 'Analytics — hero' },
  { id: 'analytics-report', module: 'analytics', feature: 'Scheduled quality report', url: '/analytics/reports/dab70001-1111-4000-8000-000000000011', page: 'Analytics — reports' },
  { id: 'analytics-explore', module: 'analytics', feature: 'Data explorer', url: '/analytics/explore', actions: [{ click: '[role="combobox"]:has-text("Choose what to measure")' }, { fill: 'input[placeholder="Search…"]', value: 'by severity' }, { click: '[role="option"]:has-text("Nonconformances by severity")' }, { click: '[role="combobox"]:has-text("Single number")' }, { click: '[role="option"]:has-text("Ranked comparison")' }], page: 'Analytics — explore' },
  { id: 'analytics-custom-metrics', module: 'analytics', feature: 'Custom metrics library', url: '/analytics/metrics', page: 'Analytics — custom metrics' },
  { id: 'analytics-alerts', module: 'analytics', feature: 'Metric alerts', url: '/analytics/alerts', page: 'Analytics — alerts' },

  // ── Platform: workflows, automation, app builder, audit trail ───────────
  { id: 'workflows-templates', module: 'workflows', feature: 'Workflow templates per module', url: '/workflow-templates', page: 'Workflows — templates' },
  { id: 'workflows-builder', module: 'workflows', feature: 'Workflow template builder', url: '/workflow-templates/dac10001-1111-4000-8000-000000000002', hero: true, slots: ['workflows.hero', 'workflows.builder', 'bento.workflows'], page: 'Workflows — builder' },
  { id: 'workflows-instance-in-progress', module: 'workflows', feature: 'Workflow instance in progress: completed triage step, QA closure awaiting its approver', url: '/workflow-instances/daf30001-1111-4000-8000-000000000006', slots: ['workflows.accountability'], page: 'Workflows — live instance' },
  { id: 'workflows-approval-flows', module: 'workflows', feature: 'Approval flows', url: '/approval-flows', page: 'Workflows — approval flows' },
  { id: 'automation-rules', module: 'workflows', feature: 'Automation rules', url: '/automation-rules', slots: ['product.cap.automation', 'platform.automation'], page: 'Platform — automation' },
  { id: 'app-builder-forms', module: 'app-builder', feature: 'App Builder forms', url: '/records', actions: [{ tab: 'Forms' }], page: 'App Builder — forms' },
  { id: 'app-builder-submissions', module: 'app-builder', feature: 'App Builder submissions', url: '/records', page: 'App Builder — records' },
  { id: 'audit-trail-feed', module: 'audit-trail', feature: 'Audit trail feed — user, action, time', url: '/audit-logs', hero: true, slots: ['audit-trail.hero', 'audit-trail.capture', 'features.auditTrail', 'about.trail', 'product.cap.audit-trail', 'bento.audit', 'product.resource.3'], page: 'Audit Trail — hero' },
  { id: 'audit-trail-entry-expanded', module: 'audit-trail', feature: 'Audit entry expanded to its before/after field state', url: '/audit-logs', sql: `SELECT '/audit-logs' FROM (SELECT a.entity_type, a.entity_id FROM audit_logs a WHERE a.company_id = ${NORDIC} AND a.action = 'UPDATE' AND a.deleted_at IS NULL ORDER BY a.created_at DESC LIMIT 1) last WHERE coalesce((SELECT n.title FROM nonconformances n WHERE n.id = last.entity_id), (SELECT c.title FROM capas c WHERE c.id = last.entity_id), (SELECT r.title FROM change_requests r WHERE r.id = last.entity_id), (SELECT d.title FROM documents d WHERE d.id = last.entity_id), '') !~* '^$|email|test|e2e|firehose'`, actions: [{ click: '[aria-label="Expand change details"]:has-text("UPDATE") >> nth=0' }], focusSel: 'div:has(> [aria-expanded="true"])', blocked: 'every Nordic UPDATE audit entry was written by the EMAIL-TEST firehose / E2E runs (the newest expands to "Email Test User was assigned role"); the seeded demo records bypass the audit trigger, so there is no clean before/after diff. sql captures once the newest UPDATE is on a real NC/CAPA/CR/document', slots: ['audit-trail.tamperEvident'], page: 'Audit Trail — tamper evidence' },

  // ── Administration & governance ─────────────────────────────────────────
  { id: 'governance-role-matrix', module: 'administration', feature: 'Role permission matrix by module', url: '/roles/d3000001-1111-4000-8000-000000000007', focusSel: '#section-permissions', hero: true, slots: ['governance.hero', 'governance.matrix', 'product.cap.permissions'], page: 'Governance — hero' },
  { id: 'governance-scope-ladder', module: 'administration', feature: 'One module expanded to its access scope', url: '/roles/d3000001-1111-4000-8000-000000000007', actions: [{ click: 'button[aria-label="Customize Document Control"]' }], slots: ['governance.scopes'], page: 'Governance — scopes' },
  { id: 'administration-roles', module: 'administration', feature: 'Roles list', url: '/roles', page: 'Governance — roles' },
  { id: 'administration-users', module: 'administration', feature: 'Users', url: '/users', page: 'Administration — users' },
  { id: 'administration-user-detail', module: 'administration', feature: 'User with sites and roles', url: '/users/d2000001-1111-4000-8000-000000000001', slots: ['governance.groups'], page: 'Administration — user' },
  { id: 'administration-groups', module: 'administration', feature: 'Groups', url: '/groups', page: 'Administration — groups' },
  { id: 'administration-sites', module: 'administration', feature: 'Sites', url: '/sites', slots: ['product.cap.multi-site'], page: 'Administration — multi-site' },
  { id: 'administration-departments', module: 'administration', feature: 'Departments', url: '/departments', page: 'Administration — departments' },
  { id: 'administration-organization-security', module: 'administration', feature: 'Organization security: sign-in methods and policies', url: '/organization-security', slots: ['product.cap.e-signatures'], page: 'Security — sign-in' },
  { id: 'administration-settings', module: 'administration', feature: 'Company settings', url: '/settings', page: 'Administration — settings' },
  { id: 'administration-service-accounts', module: 'administration', feature: 'Service accounts', url: '/service-accounts', sql: `SELECT '/service-accounts' WHERE EXISTS (SELECT 1 FROM users u WHERE u.is_service_account AND u.company_id = ${NORDIC})`, blocked: 'no service accounts exist (users.is_service_account is false for every user) — the page shows "No service accounts yet"', page: 'Developers — service accounts' },
  { id: 'administration-ai-usage', module: 'administration', feature: 'AI usage and invocation log', url: '/ai-usage', actions: [{ click: 'button:has-text("Everyone")' }], slots: ['ai.trust'], page: 'AI — trust' },
  { id: 'administration-shared-records', module: 'administration', feature: 'Records shared externally', url: '/shared-records', page: 'Administration — sharing' },
  { id: 'risk-assessment-templates', module: 'risk-management', feature: 'Risk assessment templates', url: '/risk-assessment-templates', page: 'Risk — templates' },
  { id: 'rca-templates', module: 'risk-management', feature: 'Root cause analysis templates', url: '/rca-templates', slots: ['product.cap.rca'], page: 'RCA — templates' },
  { id: 'validation-centre', module: 'administration', feature: 'Validation documentation centre', url: '/validation', page: 'Validation — overview' },
]
