// PW-J2 · Full ad-hoc audit lifecycle with e-signed close-out (MTC-06/07/08).
//
// create (SCHEDULED) → start (IN_PROGRESS) → score both leaf clauses, one of
// them MAJOR_NC → auto-finding raised → close the finding → submit for close-out
// (REVIEW) → reviewer completes step 1 → approver e-signs step 2 → CLOSED.
//
// The two close-out gates are asserted on the way through, because they are the
// module's only real submit guards: every LEAF clause must carry a verdict
// (section headers are exempt — the seeded standard has one, deliberately) and
// no finding may be left open.
import { test, expect } from '../../video/fixtures/videoTest.js'
import { AUTH, USERS, AUDIT_STANDARD } from '../fixtures/cast.js'
import {
  auditRow,
  closeFinding,
  completeCloseOutReview,
  completeCloseOutSignOff,
  createAdHocAudit,
  findingsOf,
  openAuditTab,
  responsesOf,
  scoreClause,
  startAudit,
  submitForCloseOut,
  uniqueScope,
} from '../fixtures/audits.js'
import { sqlValue, waitForSqlValue } from '../fixtures/db.js'

test.use({ storageState: AUTH.author })

test.describe('PW-J2 · ad-hoc audit, executed and closed with an e-signature', () => {
  test('SCHEDULED → IN_PROGRESS → REVIEW → CLOSED, auto-finding raised and resolved', async ({
    page,
    browser,
  }) => {
    // The longest journey in the suite: create → start → score 2 clauses →
    // close a finding → submit → two workflow steps in two other browser
    // contexts, each with its own sync-back barrier. ~35s on a warm dev stack;
    // the budget is deliberately far clear of that, because every one of those
    // barriers degrades to a reload-and-retry when the stack is busy.
    test.setTimeout(600_000)

    const scope = uniqueScope('J2')
    const audit = await createAdHocAudit(page, scope)
    expect(audit.statusId, 'ad-hoc audits are created SCHEDULED, not DRAFT').toBe('SCHEDULED')
    expect(audit.auditNumber).toMatch(/^AUD-\d{4}-\d{4}$/)
    expect(
      Number(
        sqlValue(
          `SELECT jsonb_array_length(requirement_schema) FROM audit_instances WHERE id = '${audit.id}'`,
        ),
      ),
      'the standard clause list is frozen onto the audit at create time',
    ).toBe(3)

    await startAudit(page)
    expect(auditRow(audit.id).statusId).toBe('IN_PROGRESS')

    // Gate 1 — nothing assessed yet, so the submit CTA is disabled and says why.
    // Explicit timeouts: `startAudit` and the scoring steps can leave a
    // navigation in flight, and the 5s expect default lands inside it.
    const submitCta = page.getByRole('button', { name: /^Submit for Close-Out/ })
    await expect(submitCta).toBeDisabled({ timeout: 30_000 })
    await expect(submitCta).toHaveText(/2 unassessed/, { timeout: 30_000 })

    await openAuditTab(page, 'Requirements')
    await scoreClause(page, audit.id, AUDIT_STANDARD.clauses.documentControl, 'Conforming')
    await scoreClause(page, audit.id, AUDIT_STANDARD.clauses.training, 'Major NC')

    const responses = responsesOf(audit.id)
    expect(responses[AUDIT_STANDARD.clauses.documentControl.id]).toBe('CONFORMING')
    expect(responses[AUDIT_STANDARD.clauses.training.id]).toBe('MAJOR_NC')
    expect(
      responses[AUDIT_STANDARD.clauses.section.id],
      'the section header is never assessable and takes no verdict',
    ).toBeUndefined()

    // The MAJOR_NC verdict raises an auto-finding in the same transaction.
    const findings = findingsOf(audit.id)
    expect(findings, 'exactly one auto-finding for the one NC verdict').toHaveLength(1)
    const [finding] = findings
    expect(finding.autoGenerated).toBe(true)
    expect(finding.typeId).toBe('MAJOR_NC')
    expect(finding.statusId).toBe('OPEN')
    expect(finding.findingNumber).toMatch(/^FND-\d{4}-\d{4}$/)

    // Gate 2 — all clauses assessed, but the open finding still blocks close-out.
    await expect(submitCta).toBeDisabled({ timeout: 30_000 })
    await expect(submitCta).toHaveText(/1 open/, { timeout: 30_000 })

    await openAuditTab(page, 'Findings')
    await expect(page.getByText(finding.findingNumber).first()).toBeVisible({ timeout: 20_000 })
    await closeFinding(page, finding.findingNumber)
    await waitForSqlValue(
      `SELECT count(*) FROM audit_findings WHERE id = '${finding.id}' AND status_id = 'CLOSED'`,
      { timeoutMs: 30_000, label: 'finding closed' },
    )

    await submitForCloseOut(page, audit.id)
    expect(auditRow(audit.id).statusId, 'submit hands the audit to the workflow engine').toBe(
      'REVIEW',
    )
    expect(
      Number(
        sqlValue(
          `SELECT count(*) FROM workflow_instances WHERE resource_type = 'AuditInstance' AND resource_id = '${audit.id}'`,
        ),
      ),
      'close-out workflow instantiated',
    ).toBeGreaterThan(0)

    await completeCloseOutReview(browser, audit.id)
    await completeCloseOutSignOff(browser, audit.id)

    await waitForSqlValue(
      `SELECT count(*) FROM audit_instances WHERE id = '${audit.id}' AND status_id = 'CLOSED'`,
      { timeoutMs: 90_000, label: 'audit CLOSED by the workflow engine' },
    )
    const closed = auditRow(audit.id)
    expect(closed.statusId).toBe('CLOSED')
    expect(closed.completedAt, 'completed_at stamped on close').toBeTruthy()

    // Part 11 — the sign-off step's e-signature is recorded against the task,
    // signed by the approver (audits have no signature subject column of their
    // own; close-out rides the generic workflow task subject — inventory #6).
    const signatures = Number(
      sqlValue(`
        SELECT count(*) FROM signatures s
         WHERE s.user_id = '${USERS.approver.id}'
           AND s.task_instance_id IN (
             SELECT id FROM task_instances
              WHERE entity_type = 'AuditInstance' AND entity_id = '${audit.id}')`),
    )
    expect(signatures, 'the close-out approval is e-signed').toBeGreaterThan(0)

    // A CLOSED audit is terminal and read-only in the UI.
    await page.goto(`/audits/instances/${audit.id}`)
    await expect(page.getByText('This audit is closed and read-only.')).toBeVisible({
      timeout: 30_000,
    })
    await expect(page.getByRole('button', { name: /^Submit for Close-Out/ })).toHaveCount(0)
  })
})
