/**
 * Reporting-key rules for the form builder (QMS Intelligence — Phase 9).
 *
 * MIRROR, NOT AUTHORITY. The authoritative copy is
 * `backend/shared/utils/analyticsFieldProjection.js`, enforced at the schema
 * layer (`backend/api/schemas/formTemplates.js`) so a save with a bad key is
 * refused with a 400 no matter which client sent it. This copy exists so the
 * author sees the problem while typing rather than after pressing Save. Same
 * relationship as `useModuleScoring.js` to `moduleScoringService.js`: keep the
 * two in step, and treat the backend as the one that decides.
 *
 * ── WHY AN AUTO-GENERATED NAME IS REFUSED ───────────────────────────────────
 * `generateFieldName` mints `<type>_<n>` where n is the lowest integer not
 * currently in use. That makes the name positional rather than identifying:
 * delete `number_3` and add another Number field, and the generator hands the
 * new field the freed `number_3`. A metric points at a key, so the historical
 * chart keeps drawing, keeps looking healthy, and is now measuring a different
 * question — no error, nothing blank, just a wrong number.
 *
 * The field's own name is NOT renamed to fix this and must not be: answers in
 * `records.payload` are keyed by `field.name`, so renaming a field orphans every
 * answer already saved under it. The reporting key is a separate identity —
 * the name binds answers, the key binds metrics.
 */
import { FIELD_TYPES } from '@/constants/formBuilderConfig'

// 3-64 chars, lowercase snake_case, starting with a letter. Deliberately narrow:
// this string ends up on a dashboard axis and inside a metric definition, and
// widening the rule later is free while narrowing it invalidates keys already
// projected into analytics_field_values.
const REPORTING_KEY_RE = /^[a-z][a-z0-9_]{2,63}$/

// Every prefix generateFieldName can emit — it builds them with
// `type.toLowerCase()`, so this is exactly the FIELD_TYPES key set. 'radio' is
// an alias of 'select' that never appears in FIELD_TYPES but does appear on real
// field nodes, so it is added explicitly.
const BUILDER_TYPE_NAMES = [...Object.keys(FIELD_TYPES).map((t) => t.toLowerCase()), 'radio']

/** Types a "Report on this field" flag may be set on. Mirrors isReportableType. */
export const REPORTABLE_TYPES = new Set([
  'input',
  'textarea',
  'textEditor',
  'email',
  'phone',
  'number',
  'slider',
  'rating',
  'checkbox',
  'toggle',
  'select',
  'radio',
  'optionGroup',
  'lookup',
  'datetime',
])

/**
 * Is this the key the builder would have minted? Checks the field's own type
 * exactly, then any known builder type — which catches a key pasted across from
 * another field, e.g. `select_2` sitting on a Number.
 */
export function isAutoGeneratedKey(key, type) {
  if (typeof key !== 'string' || !key) return false
  if (new RegExp(`^${String(type || '').toLowerCase()}_\\d+$`).test(key)) return true
  return BUILDER_TYPE_NAMES.some((t) => new RegExp(`^${t}_\\d+$`).test(key))
}

/**
 * Validate one field's reporting key against its siblings.
 * Returns an error string, or '' when it is fine.
 *
 * @param {string} key     the candidate key
 * @param {string} type    the field's type
 * @param {string[]} takenKeys keys already used by OTHER reportable fields
 */
export function reportingKeyError(key, type, takenKeys = []) {
  const trimmed = typeof key === 'string' ? key.trim() : ''
  if (!trimmed) return 'A reportable field needs a stable key that metrics can point at.'
  if (isAutoGeneratedKey(trimmed, type)) {
    return `"${trimmed}" is an auto-generated name. Those get reused when a field is deleted, which silently re-points a metric at different data. Use something meaningful, e.g. "defect_count".`
  }
  if (!REPORTING_KEY_RE.test(trimmed)) {
    return 'Use 3-64 characters: lowercase letters, digits and underscores, starting with a letter.'
  }
  if (takenKeys.includes(trimmed)) {
    return `"${trimmed}" is already used by another field on this form. A reporting key identifies one field.`
  }
  return ''
}

/**
 * A suggested key from a field's label — a starting point the author edits, not
 * a default they can silently accept. Returns '' when the label is missing or
 * slugs to something that would itself be rejected, so the field stays visibly
 * empty rather than pre-filled with junk.
 */
export function suggestReportingKey(label, type) {
  const slug = String(label || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 64)
  if (!slug) return ''
  return reportingKeyError(slug, type) ? '' : slug
}

/** Collect every reporting key in a schema except the one on `exceptField`. */
export function otherReportingKeys(schema, exceptField) {
  const keys = []
  const visit = (node) => {
    if (!node || typeof node !== 'object') return
    if (Array.isArray(node.children)) {
      node.children.forEach(visit)
      return
    }
    if (node === exceptField) return
    const key = node.reporting?.enabled && node.reporting?.key?.trim()
    if (key) keys.push(key)
  }
  ;(Array.isArray(schema) ? schema : []).forEach(visit)
  return keys
}
