import { currentSession } from '@/utils/currentSession'
import { BaseModel, ClientModel, Property } from '@syncEngine/index'
import { DateTime } from 'luxon'

/**
 * AuditFinding — first-class finding entity. Can spawn NC / CAPA /
 * Training / Change Request via the spawned_* FK columns; multiple
 * spawns per finding allowed, with additional cross-module links
 * captured on AuditEvidenceLink.
 *
 * findingTypeId values: MAJOR_NC / MINOR_NC / OBSERVATION / OFI
 * statusId    values: OPEN / IN_REVIEW / IN_REMEDIATION / VERIFIED / CLOSED / CANCELLED
 */
@ClientModel('auditFindings', {
  primaryKey: 'id',
  syncField: 'updatedAt',
  customIndex:
    'companyId, auditInstanceId, statusId, findingTypeId, categoryId, supplierId, assignedToUserId',
})
export class AuditFinding extends BaseModel {
  static paranoid = true

  constructor(...args) {
    super(...args)
    if (!this.companyId) this.companyId = currentSession.value?.companyId || ''
    if (!this.createdBy) this.createdBy = currentSession.value?.userId || ''
    if (!this.id) this.id = crypto.randomUUID()
  }

  @Property({ type: String, uuid: true, required: true }) id = ''
  @Property({ type: String, required: true }) companyId = ''
  @Property({ type: String, required: true }) auditInstanceId = ''
  @Property({ type: String }) auditRequirementResponseId = ''
  /** Which auditor report raised this finding (auditee flow); null otherwise. */
  @Property({ type: String }) auditReportId = /** @type {String} */ (null)
  @Property({ type: String }) findingNumber = ''
  @Property({ type: Boolean }) autoGenerated = false
  @Property({ type: String, required: true }) findingTypeId = ''
  // AUDIT-C1 (client half): status is server-enforced by the
  // enforce_audit_finding_status_transition trigger; block the generated update
  // mutation from ever carrying statusId (finding status changes go through the
  // REST respond/complete/update-status actions).
  @Property({ type: String, required: true, excludeFromGraphQL: ['update'] }) statusId = 'OPEN'
  @Property({ type: String }) categoryId = ''
  @Property({ type: String, required: true }) description = ''
  // Rich finding body (#29) — Finding Notes HTML; preserves formatting/images.
  @Property({ type: String }) detailsHtml = ''
  @Property({ type: Number }) severityScore = 1
  @Property({ type: Number }) riskScore = 1
  @Property({ type: String }) departmentId = ''
  @Property({ type: String }) supplierId = ''
  @Property({ type: String }) processArea = ''
  @Property({ type: String }) assignedToUserId = ''
  @Property({ type: DateTime }) dueDate = /** @type {DateTime} */ (null)

  // Cross-module spawn FKs.
  @Property({ type: String }) spawnedNcId = ''
  @Property({ type: String }) spawnedCapaId = ''
  @Property({ type: String }) spawnedChangeRequestId = ''
  @Property({ type: String }) spawnedTrainingInstanceId = ''

  // Supplier remediation (#7): CAPA/response + expected completion; overdue derived.
  @Property({ type: String }) responseText = ''
  @Property({ type: DateTime }) expectedCompletionDate = /** @type {DateTime} */ (null)
  @Property({ type: DateTime }) completedAt = /** @type {DateTime} */ (null)
  @Property({ type: String }) completedBy = ''

  @Property({ type: String }) createdBy = ''
  @Property({ type: DateTime }) closedAt = /** @type {DateTime} */ (null)
  @Property({ type: String }) closedBy = ''
  @Property({ type: DateTime }) deletedAt = /** @type {DateTime} */ (null)
  @Property({ type: DateTime, required: true, timestamp: true })
  createdAt = /** @type {DateTime} */ (null)
  @Property({ type: DateTime, required: true, timestamp: true, autoUpdate: true })
  updatedAt = /** @type {DateTime} */ (null)
}
